# Linux to Win32 cross with mingw-w64

TARGET = vlink.exe
DIR = objects
MD = mkdir

CC = i686-w64-mingw32-gcc
CCOUT = -o $(DUMMYVARIABLE)    # produces the string "-o "
COPTS = -std=c9x -O2 -fomit-frame-pointer -c
CONFIG =

LD = i686-w64-mingw32-gcc
LDOUT = -o $(DUMMYVARIABLE)    # produces the string "-o "
LDOPTS = -s
LIBS =


include make.rules
